name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Bridle
      run: |
        python -m pip --verbose install .

    - name: Checkout OpenDDS
      uses: actions/checkout@v2
      with:
        repository: 'objectcomputing/OpenDDS'
        path: 'OpenDDS'

    - name: Run Tests
      run: |
        DDS_ROOT=OpenDDS python tests/test.py --verbose

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --show-source --doctests --statistics
      if: always()
