name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.9, 3.11]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Bridle
      run: |
        python -m pip --verbose install .

    # - name: Checkout OpenDDS
    #   uses: actions/checkout@v2
    #   with:
    #     repository: 'objectcomputing/OpenDDS'
    #     path: 'OpenDDS'

    # - name: Checkout ACE/TAO
    #   uses: actions/checkout@v2
    #   with:
    #     repository: 'DOCGroup/ACE_TAO'
    #     path: 'OpenDDS/ACE_TAO'

    - name: Run Tests
      run: |
        # DDS_ROOT=OpenDDS python tests/test.py --verbose
        python -m unittest

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --show-source --doctests --statistics
      if: always()
